### ISSUE TITLE
SonarCloud

### ISSUE THREAD

**Issue by MeIidon** [BME-MIT-IET/iet-hf-2022-almafa#1]
Minden push után fusson le a SonarCloud ellenőrzése a [laboron](https://ftsrg.mit.bme.hu/rete-lab-lecture-notes/ivt-lab5-static-exercises.html) tanult módon.

**Comment by balintgerinm** [comment]
SolarLint inicializálásához nincs jogosultságunk, ezért Teamsen kérek segítséget.

**Comment by balintgerinm** [comment]
> 

Megérkezett a segítség.

**Comment by MeIidon** [comment]
Az elvégzett munka rövid dokumentációját a saját GitHub tárhely doc könyvtárába rakott fájlba kell írni.
Ezt még kérlek pótoljad!

**Comment by balintgerinm** [comment]
Elkészült a dokumentáció
